export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_ADD_FAVOURITE_REQUEST = 'USER_ADD_FAVOURITE_REQUEST'
export const USER_ADD_FAVOURITE_SUCCESS = 'USER_ADD_FAVOURITE_SUCCESS'
export const USER_ADD_FAVOURITE_FAIL = 'USER_ADD_FAVOURITE_FAIL'

export const USER_DELETE_FAVOURITE_REQUEST = 'USER_DELETE_FAVOURITE_REQUEST'
export const USER_DELETE_FAVOURITE_SUCCESS = 'USER_DELETE_FAVOURITE_SUCCESS'
export const USER_DELETE_FAVOURITE_FAIL = 'USER_DELETE_FAVOURITE_FAIL'

export const USER_FAVOURITE_LIST_REQUEST = 'USER_FAVOURITE_LIST_REQUEST'
export const USER_FAVOURITE_LIST_SUCCESS = 'USER_FAVOURITE_LIST_SUCCESS'
export const USER_FAVOURITE_LIST_FAIL = 'USER_FAVOURITE_LIST_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL'
